### ISSUE TITLE
Callbacks allowing variable capture

### ISSUE THREAD

**Issue by JulienNevo** [suzukiplan/z80#38]
First of all, thanks for your great emulator. I'm trying to integrate it, but I had to modify the code to make it fit to my need. I simply want the emulator to stop whenever a special instruction is met:

```
    z80.addBreakOperand(0xff, [&]() {
        z80.requestBreak();
    });
```

However, the way the callback is declared does not allow the capture ([&]), making the inner method unable to reach the z80 object.

My solution is as follow:

Instead of:
`    void addBreakOperand(unsigned char operandNumber, void (*callback)(void*) = NULL)`
I did:
`    void addBreakOperand(unsigned char operandNumber, const std::function<void()>& callback)`
and so on.

Does something like that makes sense to you? It could be applied to all the callbacks.

**Comment by JulienNevo** [comment]
HI again,

The same could be done for the Z80 constructor. Instead of using old-school and rather hard-to-read void pointers, we could use:
```
Z80(...
       std::function<void(unsigned char port, unsigned char value)> outPort,
       &mmu);
```

**Comment by suzukiplan** [comment]
Thanks for your report.
We are considering a fix in https://github.com/suzukiplan/z80/pull/39 to make the function pointer to std::function.

**Comment by suzukiplan** [comment]
I'm reopening this once because of the std::function performance issue in issue #45 , and I may make significant changes to the way read/write/in/out callbacks are set up.

**Comment by suzukiplan** [comment]
Since it is difficult to solve the performance problem with `std::function`, we are fixing it so that the default is the function pointer as before, but `std::function` can be used optionally.

This is being fixed in commit https://github.com/suzukiplan/z80/pull/43/commits/e3975389c804f2b410e35616257f3a0ff85dc8b1 of Pull Request https://github.com/suzukiplan/z80/pull/43
