### ISSUE TITLE
Callback on each instruction

### ISSUE THREAD

**Issue by JulienNevo** [suzukiplan/z80#40]
One feature I'd like would be a callback called every time an instruction is read, with a least the opcode. If the values could be shown too (if relevant), the better.

My use-case is as follows:
- On Amstrad CPC, the Z80 timing is different and I'd like to count precisely how many cycles are spent after my code is executed. What I am doing right now is hacking a counter which increases on every instruction. This forces me to modify the emulator code. Such callback would externalize my code.

One problem I see in the current implementation is that, for IX/IY instructions, only the prefix (0xdd, 0xed, 0xfd...) is transmitted (in the BreakOperand callback for example), the rest of the opcode is "lost", so this would have to be corrected first.

**Comment by suzukiplan** [comment]
Thank you for your report.

I'm aware of the need for addBreakOperand support for multibyte instructions. I took action on commit https://github.com/suzukiplan/z80/pull/39/commits/c833329e24cb5f2ce2069c802a4c0e8890b906c2.

I will also consider the opcode callback. _I already have an idea, but it will take a bit of time and will be addressed in another commit._
