### ISSUE TITLE
OUTI命令のポートについて

### ISSUE THREAD

**Issue by W88DodPECuThLOl** [suzukiplan/z80#51]
Z80エミュ使わせていただいております。
物凄く使いやすく組み込むのも簡単にできました。ありがとうございます。

使っていて気になったのですが、
OUTI命令ではじめにポートアドレスのBレジスタを引いてから出力するのが正しい挙動だと思います。

下記が詳しいです。
[入出力命令のバグ？](http://sbeach.seesaa.net/article/387861468.html)

ご確認の程よろしくお願いいたします。

**Comment by suzukiplan** [comment]
ご報告ありがとうございます！
後ほど確認します 🙇‍♂️

**Comment by suzukiplan** [comment]
Pull Request https://github.com/suzukiplan/z80/pull/52 にて対策します（本日中にマージ予定です）

**Comment by W88DodPECuThLOl** [comment]
ありがとうございます。

Many thanks.
I am grateful for your support.

**Comment by W88DodPECuThLOl** [comment]
すみません、記憶が不確かで申し訳ないのですが、
INI命令のほうは、入出力を行った後にBレジスタを引くだったような気がします。
ただ、確信が持てず……なんとも歯切れが悪くすみません。
そのように修正されていたのでしたら、無視してください。

**Comment by suzukiplan** [comment]
スミマセン。
I/O共通でプリデクリメントなのかとミスリードしてました。
OUT限定の挙動だったんですね。
[mameのZ80の実装](https://github.com/mamedev/mame/blob/master/src/devices/cpu/z80/z80.cpp#L1229-L1265)もそんな感じだったので再修正します。

**Comment by suzukiplan** [comment]
https://github.com/suzukiplan/z80/pull/53 で再修正しました 🙇

**Comment by W88DodPECuThLOl** [comment]
ありがとうございます。
