### ISSUE TITLE
IN A,(n)、OUT (n),Aのポート番号について

### ISSUE THREAD

**Issue by W88DodPECuThLOl** [suzukiplan/z80#54]
お疲れ様です。（度々すみません。）
IN A,(n)、OUT (n),A命令のポート番号ですが、Bレジスタではなく、Aレジスタがポートの上位8ビットになります。

例えば
 LD A,$1A
 IN A,($01)
とすると、16ビットのポート番号は$1A01となります。

mameのZ80より
https://github.com/mamedev/mame/blob/master/src/devices/cpu/z80/z80.cpp
3183行目

> OP(op,db) { unsigned n = arg() | (A << 8); A = in(n); WZ = n + 1;                 } /* IN   A,(n)       */

3174行目

> OP(op,d3) { unsigned n = arg() | (A << 8); out(n, A); WZ_L = ((n & 0xff) + 1) & 0xff;  WZ_H = A;   } /* OUT  (n),A       */

**Comment by suzukiplan** [comment]
ご報告ありがとうございます 🙇 
Pull Request https://github.com/suzukiplan/z80/pull/55 にて修正します。

**Comment by W88DodPECuThLOl** [comment]
迅速なご対応ありがとうござました。
